README.md
=> chore: minor readme tweaks

.github/PULL_REQUEST_TEMPLATE.md
---
title: "RFC: #<rfc#> <title>" 
---
---
=> chore: "management/rfc" label in RFC pull request template

.github/workflows/render-table.yml, README.md, text/0049-continuous-delivery.md, text/0092-asset-publishing.md, tools/rfc-render/.gitignore, tools/rfc-render/inject-table.js, tools/rfc-render/package-lock.json, tools/rfc-render/package.json, tools/rfc-render/render-rfc-table.js
A github workflow that tracks issue changes and updates the README file with a nice markdown table that lists all of our RFCs and their status.
---
=> Render an RFC table in the README

.github/ISSUE_TEMPLATE/tracking-issue.md
Reflect label change from "tracking issue" to "management/tracking" to match all the other repos.
---
title: "RFC: #<rfc#> <title>" 
labels: management/rfc
---
[Rendered version](/my-fork/text/xxxx.md)
---
=> Update label in tracking-issue.md

text/0107-construct-library-module-lifecycle.md
Added instructions on creating the graduation issue task list.
[Rendered version](https://github.com/aws/aws-cdk-rfcs/blob/epolon/graduation-issue-checklist/text/0107-construct-library-module-lifecycle.md)
---
=> RFC: 0107 added checklist instructions

.mergify.yml
Enables Mergify application to act on Pull Requests in this repo.
---
=> chore: add mergify config file

text/0107-construct-library-module-lifecycle.md
link is not accessible and doesn't belong in this RFC.
---
=> chore: remove inaccessible link to TFC

text/0095-cognito-construct-library/working-backwards-readme.md
Found some typos while reading the RFC. PR to fix them.
* Tracking issue: (no issue)
---
=> rfc 95 - fixes typos

text/0249-v2-experiments.md
- Move out discarded options to an appendix
- Move out the explanation of why can't mono-CDK main modules break backwards compatibility into an appendix
- Clarified what does `@experimental` mean in mono-CDK
- Moved out the data on modules with unstable dependencies into an appendix
[Rendered version](https://github.com/skinny85/aws-cdk-rfcs/blob/experiments/review-comments/text/0249-v2-experiments.md)
---
=> Updates to "RFC 249: v2.0 Experiments"

text/0249-v2-experiments.md, text/0253-cdk-metadata-v2.md
=> chore: lint fixes

text/0049-continuous-delivery.md
* Tracking issue: #
* [Rendered version](/my-branch/text/xxxx.md)
"asses" => "assets"
=> Typo error in 0049-continuous-delivery.md

text/359-construct-hub-deny-list.md
This is a request for comments about supporting a deny list in Construct Hub. See #359 for
APIs are signed off by @RomainMuller.
---
=> RFC 359: Construct Hub Deny List

text/0006-monolothic-packaging.md
=> extremely minor typo fix

text/0052-resource-importing-support.md
This is a request for comments about "Support importing resources". See #52 for
[Rendered version](https://github.com/tomas-mazak/aws-cdk-rfcs/blob/0052-resource-importing-support/text/0052-resource-importing-support.md)
APIs are signed off by @rix0rrr .
---
=> RFC 52: Support for importing existing resources into a CDK stack

README.md, text/0436-gamelift-l2.md
This is a request for comments about Amazon Gamelift L2 Construct. See #436 for
APIs are signed off by @otaviomacedo.
---
=> Amazon Gamelift L2 Construct RFC #436 documentation

text/0039-reduce-module-size.md, text/0063-precreated-roles.md
- Add empty lines to Reduce Module Size
- Wrap lines to 150 characters in Precreated Roles
---
=> chore: fix lint.sh errors

README.md
Documentation at
https://github.com/aws/aws-cdk/wiki/Security-And-Safety-Dev-Guide
---
=> RFC 63: Done

.github/workflows/pr-lint.yml, .github/workflows/render-table.yml
This PR is adding functionality to manually trigger repo's existing github actions.
---
=> chore: add manual trigger for github actions

.github/workflows/pr-lint.yml, .github/workflows/render-table.yml
Fix the automation for updating the table
---
=> chore: fix table update automation

README.md, lint.sh
=> chore: update readme link

.github/workflows/pr-lint.yml, README.md
This workflow only needs contents-read and nothing else.
---
=> chore: remove workflow permissions

.github/workflows/pr-lint.yml
=> chore: checkout the right commit to lint

text/0049-continuous-delivery.md
=> chore: change bucket names

.github/ISSUE_TEMPLATE/committee-suggestion.yml
=> feat: a new form to suggest working group ideas for the contributor council

text/0732-cdk-cli-telemetry.md
=> chore: updates to cdk cli telemetry RFC
