aws/aws-cdk-rfcs

.github/workflows/render-table.yml, tools/rfc-render/inject-table.js, tools/rfc-render/render-rfc-table.js
Implements a GitHub workflow which automatically renders a table of RFCs in README.
---
=> Automatically render RFC table in README when issues change

text/0049-continuous-delivery.md, text/0092-asset-publishing.md
Originally, we planned to disallow the use of assets by environment-agnostic stacks (e.g. stacks that are defined with pseudo ACCOUNT/REGION in `env`). The problem is that today this is the default behavior for `new Stack()`, which obviously can't work. The original plan was to modify the default behavior of `env` (see https://github.com/aws/aws-cdk/pull/4131), and we still want to pursue this, but since this change in default behavior has potential risk involved, we wanted to decouple it from our CI/CD delivery.
Therefore, this change updates the CI/CD and cdk-assets RFCs to support assets in environment-agnostic stacks by allowing the use `${AWS::Region}` and `${AWS::AccountId}` in `assets.json`.
---
the …
=> feat(continuous-delivery): assets in environment-agnostic stacks

tools/rfc-render/render-rfc-table.js
New order:
- Final comment period
- Pending
- Ready
- Resolved
- Proposed
The rationale is that "final comment period" and "pending" are more actionable for people coming in as they have concrete chance to influence these RFCs.
=> chore: reorder RFC table

.github/workflows/pr-lint.yml, .markdownlint.json, 0000-template.md, README.md, text/0049-continuous-delivery.md, text/0055-feature-flags.md, text/0092-asset-publishing.md, tools/linters/.gitignore, tools/linters/markdownlint.json, tools/linters/package.json, tools/rfc-render/render-rfc-table.js
Use Github actions to run markdownlint for PRs. A reasonable set of
defaults are chosen and configured under `.markdownlint.json`.
Keeping the `.markdownlint.json` file in the root of the folder so that
it is picked up by VS Code markdownlint plugin by default.
Note, all changes to the markdown files are purely formatting to
conform with the markdown linter rules.
Motivations:
The main motivations is so that all RFCs meet a reasonable bar in terms
of consistency. The main violator is line width - unusually long lines
are hard to review and comment on in PRs. They also don't play very well
with text editors.
The added benefit is that some parts of markdown are flimsy such that
they need to be formatted in a particular way to be rendered correctly.
This will help users keep to that.
---
_By …
=> feat: run markdownlint for PRs

README.md
The champion idea is great, so we want to extend it to RFCs that the
core team does as well.
---
=> chore: include champion to core team RFCs as well

.github/workflows/pr-lint.yml, text/0095-cognito-construct-library.md
It seems that Github actions don't support shell globbing, so
`markdownlint` was actually looking for files name `*.md` and `**/*.md`
which obviously don't exist.
Switching to `find` and `xargs` to enumerate the files and pass them to
the `markdownlint` explicitly.
---
Proof that the linter actually works - https://github.com/aws/aws-cdk-rfcs/pull/136/checks?sha=de1c5761088d78ef5a21a3b475fe8cae586d30ae
---
=> fix: markdownlint is not actually catching lints

text/0171-cloudfront-redesign.md
---
title: "RFC: #0171 CloudFront Redesign"
labels: management/rfc
---
Proposal to redesign the @aws-cdk/aws-cloudfront module.
The current module does not adhere to the best practice naming conventions or ease-of-use patterns that are present in the other CDK modules. A redesign of the API will allow for friendly, easier access to common patterns and usages.
This RFC does not attempt to lay out the entire API; rather, it focuses on a complete re-write of the module README with a focus on the most common use cases and how they work with the new design. More detailed designs and incremental API improvements will be tracked as part of GitHub Project Board once the RFC is approved.
[Rendered version](/njlynch/aws-cdk-rfcs/blob/njlynch/rfc171/text/0171-cloudfront-redesign.md)
---
_By …
=> RFC: 171 CloudFront Redesign

text/0079-cdk-2.0.md
[Rendered version](/nija-at/v2-deprecated/text/0079-cdk-2.0.md#removal-of-deprecated-apis)
---
=> rfc 79: cdk v2.0 - deprecated APIs

text/0079-cdk-2.0.md
This reverts commit 5e40027106d04169eb569211582e9c3a9b17b174.
PR got merged before the entire team got to see it.
---
=> Revert "rfc 79: cdk v2.0 - deprecated APIs (#235)"

text/0079-cdk-2.0.md
[Rendered version](/nija-at/v2-deprecated/text/0079-cdk-2.0.md#removal-of-deprecated-apis)
---
=> rfc 79: cdk v2.0 - deprecated APIs (#235)

.mergify.yml
We don't use conventional commits in our rfc repo.
---
=> chore: remove the messaging around conventional commits

.mergify.yml
mergify config had a ^ in the label match regex,
referring to 'starts with'.
Ref: https://doc.mergify.io/conditions.html
---
=> fix: mergify does not honour 'do-not-merge' label

text/0079-cdk-2.0.md
This reverts commit ca3e74fc9d374e2057ef5a2b72e757e8dde4488d.
---
=> Revert "rfc 79: cdk v2.0 - deprecated APIs (#235) (#238)"

text/0079-cdk-2.0.md
Two changes to the RFC:
- The branch name `next` has been updated to `v2` throughout the RFC.
The name `v2` is a lot clearer on what the branch indicates than slightly
more vague `next`.
- The strategy on how deprecated APIs are handled has been revamped to
be less manual and more automated. A one-time clean up towards the end
of the project is included.
---
=> rfc 79: cdk v2.0 - change strategy on how deprecated APIs are handled

text/0192-remove-constructs-compat.md, tools/linters/markdownlint.json
The rule didn't have to be disabled. The issue was incorrect formatting of code spans.
---
=> chore: re-enable "no-space-in-code" markdown rule

text/0079-cdk-2.0.md, tools/linters/markdownlint.json
Changes:
* Added separate section for name of the monopackage and versioning scheme during alpha and developer preview phases.
[Rendered version](https://github.com/aws/aws-cdk-rfcs/blob/nija-at/cdkv2-pkgmgr-releases/text/0079-cdk-2.0.md#releasing-to-package-managers)
---
=> rfc 79: cdkv2.0 - release & versioning

text/0192-remove-constructs-compat.md
Revert the proposal to rename `node` to `construct`. See the "Rejected Work" section for details.
=> RFC 0192: Revert "node" to "construct"

0000-template.md
A proposal to reduce the complexity of RFCs by simplifying the template to a PR/FAQ format.
[Rendered version](https://github.com/aws/aws-cdk-rfcs/blob/new-rfc-template/0000-template.md)
=> chore: simplify RFC format

.prettierrc.yaml, text/0006-monolothic-packaging.md, text/00110-cli-framework-compatibility-strategy.md, text/0049-continuous-delivery.md, text/0055-feature-flags.md, text/0079-cdk-2.0.md, text/0092-asset-publishing.md, text/0095-cognito-construct-library.md, text/0107-construct-library-module-lifecycle.md, text/0171-cloudfront-redesign.md, text/0192-remove-constructs-compat.md, tools/linters/markdownlint.json
Modified linter rules and prettier config to standardize on 80 character lines. Diff viewing is somewhat difficult with the maximum set at 150, and sometimes edits are submitted by an author who has their setting at a different place like 100 or 120, which makes it hard to tell what actually changed. Since RFCs are mostly text, 80 characters seems reasonable.
=> Standardize on 80 character lines for easier diff viewing

.github/workflows/render-table.yml
The workflow currently fails with:
```
/usr/bin/git config --local --unset http.https://github.com/.extraheader ^AUTHORIZATION:
/opt/hostedtoolcache/Python/3.9.1/x64/bin/python /home/runner/work/_actions/peter-evans/create-pull-request/v2/dist/cpr/create_pull_request.py
Error: Unable to process command '::set-env name=PULL_REQUEST_NUMBER::288' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
Update to version `v3` of the `peter-evans/create-pull-request` Action,
as it does not have this problem …
=> chore: fix the 'render-table' GitHub workflow

text/204-golang-bindings.md
This updates RFC204 based on the latest developments for the
implementation thereof. In particular, the following elements have been
changed:
- Updates to *jsii enums*
- Preserve capitalisation of enum constant names, and separate from type name with `_`
- Updates to *jsii interfaces* (aka: behavioral interfaces)
- Added a go struct for the concrete jsii proxy object
- Updates to *jsii structs* (aka: datatype interfaces)
- Replaced `Iface` suffix in go interface names with an `I` prefix
- Added *Approach 3* for handling jsii struct inheritance
- Updates to *jsii classes*
- Removed `Iface` suffix from go interfaces generated for classes
- Un-exported the go struct concrete type for the jsii proxy objects
- Removed unused properties from concrete types for jsii proxy objects
- Used mock …
=> refactor(go): updates to RFC204 - golang bindings

text/0006-monolothic-packaging.md, text/0079-cdk-2.0.md
As we prepare to release Go for 1.x and 2.x, add a section to the Monolithic Packaging RFC which proposes the naming strategy.
---
=> monocdk: add golang names

text/0006-monolothic-packaging.md, text/0079-cdk-2.0.md
Realize we may need to do some different work to not disturb Java/Python users (pretend the "root" package has the name of the old `core` package).
Also realize that "no source changes" is a pipe dream as long as the new `constructs` library is involved.
---
=> RFC 6: record Python naming decisions

text/204-golang-bindings.md
Adds section on optionality for generated go code.
---
=> chore: go optional values codegen

text/0079-cdk-2.0.md
Update v2 RFC with the approach we decided on for handling packages that are shared between the CLI and the Framework.
---
=> RFC 6: Record decisions about shared packages

lint.sh, text/287-cli-deprecation-warnings.md
* Tracking issue: #287
* [Rendered version](https://github.com/skinny85/aws-cdk-rfcs/blob/feat/cli-deprecation-warnings/text/287-cli-deprecation-warnings.md)
---
=> RFC 287: CLI deprecated warnings

text/0192-remove-constructs-compat.md
Following up on c8802395, update the rest of the RFC with the change not
to rename 'node' to 'construct'.
---
=> RFC 0192: update Construct.construct with Construct.node throughout

text/0328-polyglot-assert.md
* Tracking issue: #328
* [Rendered version](https://github.com/aws/aws-cdk-rfcs/blob/nija-at/polyglot-assert/text/0328-polyglot-assert.md)
---
=> rfc 328 - polyglot assert

text/0314-cdk-construct-hub.md
Introduce design modifications pertaining to generating package documentation artifacts in the backend as opposed to the front end. 
* [Rendered version](https://github.com/aws/aws-cdk-rfcs/blob/epolon/backend-goc-generation/text/0314-cdk-construct-hub.md)
---
=> chore: construct hub - doc generation in the backend

.github/ISSUE_TEMPLATE/tracking-issue.md, .github/PULL_REQUEST_TEMPLATE.md, 0000-template.md, README.md
As a follow up to a retrospective the CDK team has performed about the RFC process. 
This PR proposes the following changes:
* Decouple the creation of the tracking issue from the submission of the RFC pull request to simplify the initial phase.
* Add a concept of "API Bar Raiser" who needs to approve the "working backwards" section of the RFC
* Remove RFC PR # from document - the tracking issue is the RFC number.
* Simplify template a little
* Add details in the main README which describes each step
* Additional minor changes
See https://github.com/cdklabs/team-internal/pull/18 for internal process changes.
=> RFC 53: updates to RFC process

text/0001-cdk-update.md
* Tracking issue: #1
* [Rendered version](https://github.com/offbyone/aws-cdk-rfcs/blob/0001-cdk-update/text/0001-cdk-update.md)
---
=> RFC 1: Faster Development Iterations (aka "CDK Watch")

text/0249-v2-experiments.expired.md, text/0249-v2-experiments.md, text/0249-v2-experiments.original.md
While working on the release of the CDK v2 Experimental Modules, I found myself looking for a place to document and discuss some of the customer-facing decisions being made (e.g., package naming, versioning, Changelog organization). Unfortunately, the current state of RFC 249 does not lend itself well to this format (IMO); the RFC as-is is more implementation-focused and more heavily leans towards the **_why_** of many of the decisions. While absolutely useful context, it doesn't read as much as a working-backwards document as I'd like.
My mental model to solve this was to copy (and save!) this really useful decision-making document, and replace the main RFC body with a series of working-backwards artifacts that (hopefully?) capture the customer experience of working with the …
=> RFC 249: Rewrite the V2 Experiments RFC to have a more working-backwards tone

text/353-cfn-registry-constructs.md
This is a proposal to publish construct libraries automatically generated for all public CloudFormation public extensions (resources/modules). See #353 for additional details.
Implementation is under: https://github.com/cdklabs/cdk-cloudformation-types
APIs are signed off by @rix0rrr 
---
=> RFC 353: Constructs for CloudFormation Extensions

text/353-cfn-registry-constructs.md
RFC 353 (https://github.com/aws/aws-cdk-rfcs/pull/356) was committed with markdownlint errors; this causes all subsequent PRs to fail on these checks.
=> fix: correct markdownlint errors in RFC 353

text/0079-cdk-2.0.md
The RFC currently specifies that post-launch of CDK v2, the v2 packages will get
an NPM distribution tag of `latest`, and the v1 packages will get a tag of
`v1`. However, tags that can be interpreted as valid semver ranges are not
allowed, and it is impossible to publish without a tag. Rename the tag to
`latest-1` to get around this. This is the same convention `npm` uses for its
releases.
---
=> chore: update CDKv2 RFC guidance for v1 dist tags post-launch

text/0308-cli-advisories.md
This is a request for comments about CLI notices. 
See #308 for additional details. 
APIs are signed off by @eladb.
[Readable version](https://github.com/aws/aws-cdk-rfcs/blob/otaviom/cli-advisories/text/0308-cli-advisories.md)
---
=> RFC 308: CLI notices

.mergify.yml
Example of error message reported by current config: https://github.com/aws/aws-cdk-rfcs/runs/4805415314
I updated the config based on the information in https://blog.mergify.com/strict-mode-deprecation/.
---
=> fix: mergify config uses deprecated "strict" mode

text/0308-cli-advisories.md
This is not a RFC.
Currently, PRs are always failed by existing lint error, so I run `lint.sh fix`. And disabled 1 rule in inline.
---
=> fix(lint): run lint.sh fix

text/287-cli-deprecation-warnings.md
The documentation for the DEPRECATED environment variable does not align
with CDKs behavior. This change corrents this misalignment:
* The environment variable is `JSII_DEPRECATED`, not `DEPRECATED`
* For CDK to throw an exception, the environment variable should have a
value of `fail`, not `error`
Addresses #414 
---
=> Corrected DEPRECATED environment variable docs

text/0063-precreated-roles.md
[Rendered version](https://github.com/aws/aws-cdk-rfcs/blob/huijbers/0063-precreated-roles/text/0063-precreated-roles.md)
Describes a mechanism for integration CDK apps with an workflow where IAM Roles cannot be created by app developers.
---
=> RFC 63: support precreated IAM Roles

text/0431-sagemaker-l2-endpoint.md
Co-authored-by: Matt McClean <mmcclean@amazon.com>
Co-authored-by: Long Yao <yl1984108@gmail.com>
Co-authored-by: Drew Jetter <60628154+jetterdj@users.noreply.github.com>
Co-authored-by: Murali Ganesh <59461079+foxpro24@users.noreply.github.com>
Co-authored-by: Abilash Rangoju <988529+rangoju@users.noreply.github.com>
This is a request for comments about SageMaker model hosting L2 constructs. See #431 for
APIs are signed off by @kaizencc.
---
[Rendered Version](https://github.com/petermeansrock/aws-cdk-rfcs/blob/sagemaker-l2-endpoint/text/0431-sagemaker-l2-endpoint.md)
---
=> RFC 431: SageMaker Model Hosting L2 Constructs

0000-template.md
IMHO it will be easier to read through the RFC if we will add a section for Customer Pains at the beginning of the RFC. 
This section should describe the customer pain only, without any implementation details.
This is a request for comments about {RFC_DESCRIPTION}. See #{TRACKING_ISSUE} for
APIs are signed off by @{BAR_RAISER}.
---
=> Add customer pains to the RFC

text/0456-elasticache-l2.md
This is a request for comments about an RFC to add L2 constructs to ElastiCache. See #456 for
APIs will be signed off by @corymhall.
---
=> Add ElastiCache L2 RFC

text/0322-cdk-pipelines-updated-api.md
Extra spacing caused linter failures.
---
=> chore: Update 0322-cdk-pipelines-updated-api.md

text/0077-import-external-resources.md, text/0264-registry-schema-codegen.md
These are two distinct RFCs for two distinct features, but we might as
well work on the docs at the same time. Hence, one PR.
* Tracking issue: #77 - importing external resources
* [Rendered version](/huijbers/0264-0077-cloudformation-registry/text/0077-import-external-resources.md)
* Tracking issue: #264 - codegen off the new registry schema
* [Rendered version](/huijbers/0264-0077-cloudformation-registry/text/0264-registry-schema-codegen.md)
---
=> RFC 77, RFC 264: CloudFormation Registry Imports

text/0499-appconfig-constructs.md
This is a request for comments about AppConfig L2 constructs. See #499 for
---
=> RFC 499: AppConfig Constructs

.github/workflows/pr-lint.yml, .github/workflows/render-table.yml
This is necessary to have any modern packages work.
Right now a Dependabot PR is failing with `no such module: 'node:fs'` 🥴.
---
=> chore: upgrade Node versions in GitHub workflows

.github/workflows/render-table.yml, ACCEPTED.md, CLOSED.md, FULL_INDEX.md, PROPOSED.md, README.md, tools/linters/package.json, tools/rfc-render/fetch-issues.js, tools/rfc-render/inject-table.js, tools/rfc-render/package-lock.json, tools/rfc-render/package.json, tools/rfc-render/render-rfc-table.js, tools/rfc-render/status.js
Currently all RFCs are listed in a single long list in the README.md
It is very unreadable and ruins the README.
This PR splits the the list into various interesting subviews, while keeping any currently relevant RFC front and center in the README.
Purely visual change.
---
=> chore: split RFC list in multiple files

.github/workflows/render-table.yml, ACCEPTED.md, CLOSED.md, FULL_INDEX.md, PROPOSED.md, README.md, tools/rfc-render/fetch-issues.js, tools/rfc-render/render-rfc-table.js
Because we are doing more requests now, we run into rate limit issues with the default `GITHUB_ACTIONS` token.
Switching to use the automation user.
Also fix a bug with the provided status order being ignored.
---
=> chore(rfc-table): order tables by provided status order and use PAT in workflows to avoid rate limits

.mergify.yml
We are using deprecated parameters that are about to be removed (October 21st, 2024).
---
=> chore(mergify): move deprecated parameters from `pull_request_rules` to `queue_rules`

text/0670-aws-applicationsignals-enablement-l2.md
This is a request for comments about adding L2 constructs for simplifying Application Signals enablement process. See https://github.com/aws/aws-cdk-rfcs/issues/670 for
APIs are signed off by @ moelasmar.
---
=> RFC 670: AWS CloudWatch Application Signals L2 Constructs for Enablement

text/0162-refactoring-support.md
This is a request for comments about CDK Refactoring Support. See #162 for
APIs are signed off by @rix0rrr.
---
=> CDK refactoring support

text/0710-node-deprecation-strategy.md
This is a request for comments about formalizing a deprecation strategy for Node.js in the AWS CDK. See https://github.com/aws/aws-cdk-rfcs/issues/710 for
[Rendered Version](https://github.com/adamjkeller/aws-cdk-rfcs/blob/nodejs-strategy/text/0710-node-deprecation-strategy.md)
---
=> RFC 710: Formalizing a Node Deprecation Strategy for AWS CDK
